/- Operational reference proof search for the four-signed propositional tableau.
   The scheduler always processes the head of a finite worklist. Processed compound
   formulas are removed; atomic formulas are accumulated in `lits`. Branching rules
   recursively explore both children. The worklist weight decreases on every child. -/
import Nullivance.Metatheory

namespace Nullivance.Operational

open Nullivance.Syntax
open Nullivance.Semantics
open Nullivance.ProofTheory
open Nullivance.Metatheory

/-- Def 3.78: one operational branch consists of formulas still to process and
an accumulated atomic constraint list. -/
structure SearchBranch where
  todo : Branch
  lits : Branch
deriving Repr

/-- The signed constraints represented by an operational branch. -/
def SearchBranch.constraints (W : SearchBranch) : Branch := W.todo ++ W.lits

/-- The reference scheduler has finished a branch exactly when its worklist is empty. -/
def SearchBranch.Terminal (W : SearchBranch) : Prop := W.todo = []

/-- Def 3.78: deterministic head expansion. A branching rule returns both children;
an atom is transferred to the atomic accumulator. -/
def children : SearchBranch → List SearchBranch
  | ⟨[], _⟩ => []
  | ⟨(S, Formula.atom n) :: rest, lits⟩ =>
      [⟨rest, (S, Formula.atom n) :: lits⟩]
  | ⟨(S, Formula.neg φ) :: rest, lits⟩ =>
      match S with
      | .Tpos => [⟨(Sign.Fpos, φ) :: rest, lits⟩]
      | .Tneg => [⟨(Sign.Fneg, φ) :: rest, lits⟩]
      | .Fpos => [⟨(Sign.Tpos, φ) :: rest, lits⟩]
      | .Fneg => [⟨(Sign.Tneg, φ) :: rest, lits⟩]
  | ⟨(S, Formula.conj φ ψ) :: rest, lits⟩ =>
      match S with
      | .Tpos => [⟨(Sign.Tpos, φ) :: (Sign.Tpos, ψ) :: rest, lits⟩]
      | .Tneg => [⟨(Sign.Tneg, φ) :: rest, lits⟩, ⟨(Sign.Tneg, ψ) :: rest, lits⟩]
      | .Fpos => [⟨(Sign.Fpos, φ) :: rest, lits⟩, ⟨(Sign.Fpos, ψ) :: rest, lits⟩]
      | .Fneg => [⟨(Sign.Fneg, φ) :: (Sign.Fneg, ψ) :: rest, lits⟩]
  | ⟨(S, Formula.disj φ ψ) :: rest, lits⟩ =>
      match S with
      | .Tpos => [⟨(Sign.Tpos, φ) :: rest, lits⟩, ⟨(Sign.Tpos, ψ) :: rest, lits⟩]
      | .Tneg => [⟨(Sign.Tneg, φ) :: (Sign.Tneg, ψ) :: rest, lits⟩]
      | .Fpos => [⟨(Sign.Fpos, φ) :: (Sign.Fpos, ψ) :: rest, lits⟩]
      | .Fneg => [⟨(Sign.Fneg, φ) :: rest, lits⟩, ⟨(Sign.Fneg, ψ) :: rest, lits⟩]
  | ⟨(S, Formula.oplus φ ψ) :: rest, lits⟩ =>
      match S with
      | .Tpos => [⟨(Sign.Tpos, φ) :: (Sign.Tpos, ψ) :: rest, lits⟩]
      | .Tneg => [⟨(Sign.Tneg, φ) :: rest, lits⟩, ⟨(Sign.Tneg, ψ) :: rest, lits⟩]
      | .Fpos => [⟨(Sign.Fpos, φ) :: (Sign.Fpos, ψ) :: rest, lits⟩]
      | .Fneg => [⟨(Sign.Fneg, φ) :: rest, lits⟩, ⟨(Sign.Fneg, ψ) :: rest, lits⟩]

/-- One reference-scheduler transition selects one of the generated children. -/
def RefStep (W W' : SearchBranch) : Prop := W' ∈ children W

/-- The termination measure: only unprocessed formula occurrences contribute. -/
def SearchBranch.weight (W : SearchBranch) : Nat := Metatheory.weight W.todo

/-- Every child generated by the reference scheduler has smaller worklist weight. -/
theorem children_weight_lt (W : SearchBranch) :
    ∀ W' ∈ children W, W'.weight < W.weight := by
  rcases W with ⟨todo, lits⟩
  cases todo with
  | nil => simp [children]
  | cons c rest =>
      rcases c with ⟨S, φ⟩
      cases φ <;> cases S <;>
        simp [children, SearchBranch.weight, Metatheory.weight, Metatheory.fsize] <;> omega

/-- Every reference transition strictly decreases the worklist measure. -/
theorem refStep_weight_lt {W W' : SearchBranch} (h : RefStep W W') :
    W'.weight < W.weight :=
  children_weight_lt W W' h

/-- The reference transition relation is well founded because it is contained in
the inverse image of strict order on natural-valued worklist weights. -/
theorem refStep_wellFounded : WellFounded (fun W' W => RefStep W W') :=
  (WellFounded.onFun (f := SearchBranch.weight) Nat.lt_wfRel.wf).mono
    (fun _ _ h => refStep_weight_lt h)

/-- Def 3.79: exhaustive depth-first execution of the reference scheduler.
The result lists all terminal atomic branches. -/
def run : Branch → Branch → List Branch
  | [], lits => [lits]
  | (S, Formula.atom n) :: rest, lits =>
      run rest ((S, Formula.atom n) :: lits)
  | (S, Formula.neg φ) :: rest, lits =>
      match S with
      | .Tpos => run ((Sign.Fpos, φ) :: rest) lits
      | .Tneg => run ((Sign.Fneg, φ) :: rest) lits
      | .Fpos => run ((Sign.Tpos, φ) :: rest) lits
      | .Fneg => run ((Sign.Tneg, φ) :: rest) lits
  | (S, Formula.conj φ ψ) :: rest, lits =>
      match S with
      | .Tpos => run ((Sign.Tpos, φ) :: (Sign.Tpos, ψ) :: rest) lits
      | .Tneg => run ((Sign.Tneg, φ) :: rest) lits ++ run ((Sign.Tneg, ψ) :: rest) lits
      | .Fpos => run ((Sign.Fpos, φ) :: rest) lits ++ run ((Sign.Fpos, ψ) :: rest) lits
      | .Fneg => run ((Sign.Fneg, φ) :: (Sign.Fneg, ψ) :: rest) lits
  | (S, Formula.disj φ ψ) :: rest, lits =>
      match S with
      | .Tpos => run ((Sign.Tpos, φ) :: rest) lits ++ run ((Sign.Tpos, ψ) :: rest) lits
      | .Tneg => run ((Sign.Tneg, φ) :: (Sign.Tneg, ψ) :: rest) lits
      | .Fpos => run ((Sign.Fpos, φ) :: (Sign.Fpos, ψ) :: rest) lits
      | .Fneg => run ((Sign.Fneg, φ) :: rest) lits ++ run ((Sign.Fneg, ψ) :: rest) lits
  | (S, Formula.oplus φ ψ) :: rest, lits =>
      match S with
      | .Tpos => run ((Sign.Tpos, φ) :: (Sign.Tpos, ψ) :: rest) lits
      | .Tneg => run ((Sign.Tneg, φ) :: rest) lits ++ run ((Sign.Tneg, ψ) :: rest) lits
      | .Fpos => run ((Sign.Fpos, φ) :: (Sign.Fpos, ψ) :: rest) lits
      | .Fneg => run ((Sign.Fneg, φ) :: rest) lits ++ run ((Sign.Fneg, ψ) :: rest) lits
termination_by todo => Metatheory.weight todo
decreasing_by all_goals simp [Metatheory.weight, Metatheory.fsize] <;> omega

/-- A branch is atomic when every formula occurrence in it is an atom. -/
def AtomicBranch (B : Branch) : Prop :=
  ∀ sφ ∈ B, ∃ n, sφ.2 = Formula.atom n

/-- Starting with an atomic accumulator, reference execution returns only atomic
terminal branches. -/
theorem run_leaves_atomic (todo lits : Branch) (hlits : AtomicBranch lits) :
    ∀ L ∈ run todo lits, AtomicBranch L := by
  revert hlits
  induction todo, lits using run.induct with
  | case1 lits => simp [run]
  | case2 S n rest lits ih =>
      intro hlits
      rw [run]
      apply ih
      intro sφ hmem
      rcases List.mem_cons.mp hmem with rfl | hmem
      · exact ⟨n, rfl⟩
      · exact hlits _ hmem
  | case3 φ rest lits ih => simpa [run] using ih
  | case4 φ rest lits ih => simpa [run] using ih
  | case5 φ rest lits ih => simpa [run] using ih
  | case6 φ rest lits ih => simpa [run] using ih
  | case7 φ ψ rest lits ih => simpa [run] using ih
  | case8 φ ψ rest lits ih1 ih2 =>
      intro hlits L hmem
      rw [run] at hmem
      rcases List.mem_append.mp hmem with hmem | hmem
      · exact ih1 hlits L hmem
      · exact ih2 hlits L hmem
  | case9 φ ψ rest lits ih1 ih2 =>
      intro hlits L hmem
      rw [run] at hmem
      rcases List.mem_append.mp hmem with hmem | hmem
      · exact ih1 hlits L hmem
      · exact ih2 hlits L hmem
  | case10 φ ψ rest lits ih => simpa [run] using ih
  | case11 φ ψ rest lits ih1 ih2 =>
      intro hlits L hmem
      rw [run] at hmem
      rcases List.mem_append.mp hmem with hmem | hmem
      · exact ih1 hlits L hmem
      · exact ih2 hlits L hmem
  | case12 φ ψ rest lits ih => simpa [run] using ih
  | case13 φ ψ rest lits ih => simpa [run] using ih
  | case14 φ ψ rest lits ih1 ih2 =>
      intro hlits L hmem
      rw [run] at hmem
      rcases List.mem_append.mp hmem with hmem | hmem
      · exact ih1 hlits L hmem
      · exact ih2 hlits L hmem
  | case15 φ ψ rest lits ih => simpa [run] using ih
  | case16 φ ψ rest lits ih1 ih2 =>
      intro hlits L hmem
      rw [run] at hmem
      rcases List.mem_append.mp hmem with hmem | hmem
      · exact ih1 hlits L hmem
      · exact ih2 hlits L hmem
  | case17 φ ψ rest lits ih => simpa [run] using ih
  | case18 φ ψ rest lits ih1 ih2 =>
      intro hlits L hmem
      rw [run] at hmem
      rcases List.mem_append.mp hmem with hmem | hmem
      · exact ih1 hlits L hmem
      · exact ih2 hlits L hmem

/-- Reference execution preserves and reflects satisfiability: the current
constraints have a model exactly when one returned terminal branch has a model. -/
theorem satBranch_constraints_iff_run (v : Nat → V4) (todo lits : Branch) :
    satBranch v (todo ++ lits) ↔
      ∃ L ∈ run todo lits, satBranch v L := by
  induction todo, lits using run.induct with
  | case1 lits => simp [run]
  | case2 S n rest lits ih =>
      rw [run, ← ih]
      constructor
      · intro h sφ hmem
        apply h sφ
        simp only [List.mem_append, List.mem_cons] at hmem ⊢
        tauto
      · intro h sφ hmem
        apply h sφ
        simp only [List.mem_append, List.mem_cons] at hmem ⊢
        tauto
  | case3 φ rest lits ih =>
      rw [run, ← ih]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.neg]
  | case4 φ rest lits ih =>
      rw [run, ← ih]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.neg]
  | case5 φ rest lits ih =>
      rw [run, ← ih]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.neg]
  | case6 φ rest lits ih =>
      rw [run, ← ih]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.neg]
  | case7 φ ψ rest lits ih =>
      rw [run, ← ih]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.conj]
      tauto
  | case8 φ ψ rest lits ih1 ih2 =>
      rw [run]
      simp only [List.mem_append, or_and_right, exists_or]
      rw [← ih1, ← ih2]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.conj]
      tauto
  | case9 φ ψ rest lits ih1 ih2 =>
      rw [run]
      simp only [List.mem_append, or_and_right, exists_or]
      rw [← ih1, ← ih2]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.conj]
      tauto
  | case10 φ ψ rest lits ih =>
      rw [run, ← ih]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.conj]
      tauto
  | case11 φ ψ rest lits ih1 ih2 =>
      rw [run]
      simp only [List.mem_append, or_and_right, exists_or]
      rw [← ih1, ← ih2]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.disj]
      tauto
  | case12 φ ψ rest lits ih =>
      rw [run, ← ih]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.disj]
      tauto
  | case13 φ ψ rest lits ih =>
      rw [run, ← ih]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.disj]
      tauto
  | case14 φ ψ rest lits ih1 ih2 =>
      rw [run]
      simp only [List.mem_append, or_and_right, exists_or]
      rw [← ih1, ← ih2]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.disj]
      tauto
  | case15 φ ψ rest lits ih =>
      rw [run, ← ih]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.oplus]
      tauto
  | case16 φ ψ rest lits ih1 ih2 =>
      rw [run]
      simp only [List.mem_append, or_and_right, exists_or]
      rw [← ih1, ← ih2]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.oplus]
      tauto
  | case17 φ ψ rest lits ih =>
      rw [run, ← ih]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.oplus]
      tauto
  | case18 φ ψ rest lits ih1 ih2 =>
      rw [run]
      simp only [List.mem_append, or_and_right, exists_or]
      rw [← ih1, ← ih2]
      simp [satBranch_cons, sat4, eval, V4.sat, V4.oplus]
      tauto

/-- Boolean closure test for a terminal atomic branch. -/
def branchClosedB (B : Branch) : Bool :=
  B.any fun sφ => decide ((sφ.1.opp, sφ.2) ∈ B)

/-- The executable closure test recognizes exactly the declarative closure predicate. -/
theorem branchClosedB_eq_true_iff (B : Branch) :
    branchClosedB B = true ↔ BranchClosed B := by
  constructor
  · intro h
    simp only [branchClosedB, List.any_eq_true] at h
    obtain ⟨⟨S, φ⟩, hmem, hopp⟩ := h
    simp only [decide_eq_true_eq] at hopp
    cases S with
    | Tpos => exact .closeT hmem hopp
    | Tneg => exact .closeT hopp hmem
    | Fpos => exact .closeF hmem hopp
    | Fneg => exact .closeF hopp hmem
  · intro h
    cases h with
    | closeT hpos hneg =>
        simp only [branchClosedB, List.any_eq_true]
        exact ⟨(Sign.Tpos, _), hpos, by simpa⟩
    | closeF hpos hneg =>
        simp only [branchClosedB, List.any_eq_true]
        exact ⟨(Sign.Fpos, _), hpos, by simpa⟩

/-- An open atomic branch is satisfied by the canonical valuation read from its
positive atomic signs. -/
theorem atomic_open_canonical_sat {B : Branch} (hatomic : AtomicBranch B)
    (hopen : ¬ BranchClosed B) : satBranch (canonicalVal B) B := by
  intro sφ hmem
  rcases sφ with ⟨S, φ⟩
  obtain ⟨n, hn⟩ := hatomic _ hmem
  dsimp at hn
  subst hn
  cases S with
  | Tpos => simp [sat4, eval, V4.sat, canonicalVal, hmem]
  | Tneg =>
      have hnot : (Sign.Tpos, Formula.atom n) ∉ B :=
        fun hpos => hopen (.closeT hpos hmem)
      simp [sat4, eval, V4.sat, canonicalVal, hnot]
  | Fpos => simp [sat4, eval, V4.sat, canonicalVal, hmem]
  | Fneg =>
      have hnot : (Sign.Fpos, Formula.atom n) ∉ B :=
        fun hpos => hopen (.closeF hpos hmem)
      simp [sat4, eval, V4.sat, canonicalVal, hnot]

/-- For atomic branches, semantic unsatisfiability is equivalent to the syntactic
complementary-pair closure condition. -/
theorem atomic_unsat_iff_closed {B : Branch} (hatomic : AtomicBranch B) :
    (∀ v, ¬ satBranch v B) ↔ BranchClosed B := by
  constructor
  · intro hunsat
    by_contra hopen
    exact hunsat (canonicalVal B) (atomic_open_canonical_sat hatomic hopen)
  · intro hclosed
    cases hclosed with
    | closeT hpos hneg =>
        exact Nullivance.Metatheory.Closes.unsat (Closes.closeT hpos hneg)
    | closeF hpos hneg =>
        exact Nullivance.Metatheory.Closes.unsat (Closes.closeF hpos hneg)

/-- Def 3.79: the reference search succeeds iff every terminal branch closes. -/
def referenceCloses (B : Branch) : Bool :=
  (run B []).all branchClosedB

/-- Boolean reference success means that every returned terminal branch satisfies
the declarative leaf-closure predicate. -/
theorem referenceCloses_eq_true_iff (B : Branch) :
    referenceCloses B = true ↔
      ∀ L ∈ run B [], BranchClosed L := by
  simp [referenceCloses, branchClosedB_eq_true_iff]

/-- The reference search succeeds exactly on semantically unsatisfiable branches. -/
theorem referenceCloses_iff_unsat (B : Branch) :
    referenceCloses B = true ↔ ∀ v, ¬ satBranch v B := by
  constructor
  · intro hsuccess v hsat
    have hrun : ∃ L ∈ run B [], satBranch v L :=
      (satBranch_constraints_iff_run v B []).mp (by simpa using hsat)
    obtain ⟨L, hL, hsatL⟩ := hrun
    have hclosed := (referenceCloses_eq_true_iff B).mp hsuccess L hL
    have hatomic := run_leaves_atomic B [] (by simp [AtomicBranch]) L hL
    exact (atomic_unsat_iff_closed hatomic).mpr hclosed v hsatL
  · intro hunsat
    apply (referenceCloses_eq_true_iff B).mpr
    intro L hL
    have hatomic := run_leaves_atomic B [] (by simp [AtomicBranch]) L hL
    apply (atomic_unsat_iff_closed hatomic).mp
    intro v hsatL
    apply hunsat v
    simpa using (satBranch_constraints_iff_run v B []).mpr ⟨L, hL, hsatL⟩

/-- A failed reference search returns a concrete open atomic leaf whose canonical
valuation satisfies both that leaf and the original branch. -/
theorem referenceCloses_false_countermodel {B : Branch}
    (hfail : referenceCloses B = false) :
    ∃ L ∈ run B [], ¬ BranchClosed L ∧
      satBranch (canonicalVal L) L ∧ satBranch (canonicalVal L) B := by
  have hnot : ¬ referenceCloses B = true := by simp [hfail]
  rw [referenceCloses_eq_true_iff] at hnot
  push Not at hnot
  obtain ⟨L, hL, hopen⟩ := hnot
  have hatomic := run_leaves_atomic B [] (by simp [AtomicBranch]) L hL
  have hsatL := atomic_open_canonical_sat hatomic hopen
  refine ⟨L, hL, hopen, hsatL, ?_⟩
  simpa using
    (satBranch_constraints_iff_run (canonicalVal L) B []).mpr ⟨L, hL, hsatL⟩

/-- Operational and declarative proof search coincide extensionally. -/
theorem referenceCloses_iff_closes (B : Branch) :
    referenceCloses B = true ↔ Closes B := by
  rw [referenceCloses_iff_unsat]
  constructor
  · exact closes_of_unsat
  · exact Nullivance.Metatheory.Closes.unsat

/- Scheduler-independent progress semantics. -/

/-- Def 3.80: a global search forest is a finite list of operational branches. -/
abbrev SearchForest := List SearchBranch

/-- A forest is terminal exactly when every branch has an empty worklist. -/
def ForestTerminal (F : SearchForest) : Prop :=
  ∀ W ∈ F, W.Terminal

/-- Every atomic accumulator in the forest satisfies its representation invariant. -/
def ForestAtomicAcc (F : SearchForest) : Prop :=
  ∀ W ∈ F, AtomicBranch W.lits

/-- A terminal forest is closed when every accumulated atomic branch closes. -/
def ForestClosed (F : SearchForest) : Prop :=
  ∀ W ∈ F, BranchClosed W.lits

/-- A valuation satisfies a search forest when it satisfies the represented constraints
of at least one active branch. -/
def ForestSat (v : Nat → V4) (F : SearchForest) : Prop :=
  ∃ W ∈ F, satBranch v W.constraints

/-- Def 3.80: one progressing scheduler step may select any nonterminal occurrence in
the forest, but it must replace that occurrence by all children generated by `children`. -/
inductive ForestStep : SearchForest → SearchForest → Prop where
  | expand {pre post : SearchForest} {W : SearchBranch} :
      ¬ W.Terminal →
      ForestStep (pre ++ W :: post) (pre ++ children W ++ post)

/-- Def 3.80: a finite progress trace is the reflexive-transitive closure of
`ForestStep`, presented with an explicit final-step constructor. -/
inductive ForestReach : SearchForest → SearchForest → Prop where
  | refl (F : SearchForest) : ForestReach F F
  | tail {F G H : SearchForest} : ForestReach F G → ForestStep G H → ForestReach F H

/-- A progressing scheduler must choose a legal successor whenever the forest is not
terminal. It has no fairness parameter because it is not permitted to stutter. -/
abbrev ProgressScheduler :=
  (F : SearchForest) → ¬ ForestTerminal F → {F' : SearchForest // ForestStep F F'}

/-- Remaining full expansion-tree size of one worklist. Unlike formula weight, this
measure accounts for duplication of the unprocessed tail at branching rules. -/
def treeCost : Branch → Nat
  | [] => 1
  | (_, Formula.atom _) :: rest => 1 + treeCost rest
  | (S, Formula.neg φ) :: rest =>
      1 + match S with
        | .Tpos => treeCost ((Sign.Fpos, φ) :: rest)
        | .Tneg => treeCost ((Sign.Fneg, φ) :: rest)
        | .Fpos => treeCost ((Sign.Tpos, φ) :: rest)
        | .Fneg => treeCost ((Sign.Tneg, φ) :: rest)
  | (S, Formula.conj φ ψ) :: rest =>
      1 + match S with
        | .Tpos => treeCost ((Sign.Tpos, φ) :: (Sign.Tpos, ψ) :: rest)
        | .Tneg => treeCost ((Sign.Tneg, φ) :: rest) +
            treeCost ((Sign.Tneg, ψ) :: rest)
        | .Fpos => treeCost ((Sign.Fpos, φ) :: rest) +
            treeCost ((Sign.Fpos, ψ) :: rest)
        | .Fneg => treeCost ((Sign.Fneg, φ) :: (Sign.Fneg, ψ) :: rest)
  | (S, Formula.disj φ ψ) :: rest =>
      1 + match S with
        | .Tpos => treeCost ((Sign.Tpos, φ) :: rest) +
            treeCost ((Sign.Tpos, ψ) :: rest)
        | .Tneg => treeCost ((Sign.Tneg, φ) :: (Sign.Tneg, ψ) :: rest)
        | .Fpos => treeCost ((Sign.Fpos, φ) :: (Sign.Fpos, ψ) :: rest)
        | .Fneg => treeCost ((Sign.Fneg, φ) :: rest) +
            treeCost ((Sign.Fneg, ψ) :: rest)
  | (S, Formula.oplus φ ψ) :: rest =>
      1 + match S with
        | .Tpos => treeCost ((Sign.Tpos, φ) :: (Sign.Tpos, ψ) :: rest)
        | .Tneg => treeCost ((Sign.Tneg, φ) :: rest) +
            treeCost ((Sign.Tneg, ψ) :: rest)
        | .Fpos => treeCost ((Sign.Fpos, φ) :: (Sign.Fpos, ψ) :: rest)
        | .Fneg => treeCost ((Sign.Fneg, φ) :: rest) +
            treeCost ((Sign.Fneg, ψ) :: rest)
termination_by todo => Metatheory.weight todo
decreasing_by all_goals simp [Metatheory.weight, Metatheory.fsize] <;> omega

/-- The cost of a live worklist is one plus the sum of the costs of all its children. -/
theorem treeCost_children (W : SearchBranch) (hlive : ¬ W.Terminal) :
    treeCost W.todo =
      1 + ((children W).map fun W' => treeCost W'.todo).sum := by
  rcases W with ⟨todo, lits⟩
  cases todo with
  | nil => exact (hlive rfl).elim
  | cons c rest =>
      rcases c with ⟨S, φ⟩
      cases φ <;> cases S <;> simp [treeCost, children]

/-- Sum of remaining full expansion-tree sizes over a forest. -/
def forestCost (F : SearchForest) : Nat :=
  (F.map fun W => treeCost W.todo).sum

/-- Every legal forest transition strictly decreases the global cost, independently of
which active branch occurrence was selected. -/
theorem forestStep_cost_lt {F F' : SearchForest} (h : ForestStep F F') :
    forestCost F' < forestCost F := by
  cases h with
  | expand hlive =>
      have hcost := treeCost_children _ hlive
      simp only [forestCost, List.map_append, List.sum_append, List.map_cons,
        List.sum_cons]
      omega

/-- The nondeterministic progressing transition is well founded. -/
theorem forestStep_wellFounded : WellFounded (fun F' F => ForestStep F F') :=
  (WellFounded.onFun (f := forestCost) Nat.lt_wfRel.wf).mono
    (fun _ _ h => forestStep_cost_lt h)

/-- There is no infinite sequence of progressing forest transitions. -/
theorem no_infinite_forestSteps :
    ¬ ∃ f : Nat → SearchForest, ∀ n, ForestStep (f n) (f (n + 1)) := by
  rintro ⟨f, hstep⟩
  have hbound : ∀ n, forestCost (f n) + n ≤ forestCost (f 0) := by
    intro n
    induction n with
    | zero => simp
    | succ n ih =>
        have hlt := forestStep_cost_lt (hstep n)
        omega
  have := hbound (forestCost (f 0) + 1)
  omega

/-- A live branch executes as the concatenation of the complete executions of all its
immediate children. This is an exhaustive syntactic check of the atomic case and all
sixteen signed connective cases. -/
theorem run_eq_flatMap_children (W : SearchBranch) (hlive : ¬ W.Terminal) :
    run W.todo W.lits =
      (children W).flatMap fun W' => run W'.todo W'.lits := by
  rcases W with ⟨todo, lits⟩
  cases todo with
  | nil => exact (hlive rfl).elim
  | cons c rest =>
      rcases c with ⟨S, φ⟩
      cases φ <;> cases S <;> simp [run, children]

/-- A live operational branch is satisfiable exactly when at least one of its immediate
children is satisfiable. -/
theorem sat_constraints_iff_children (v : Nat → V4) (W : SearchBranch)
    (hlive : ¬ W.Terminal) :
    satBranch v W.constraints ↔
      ∃ W' ∈ children W, satBranch v W'.constraints := by
  change satBranch v (W.todo ++ W.lits) ↔
    ∃ W' ∈ children W, satBranch v W'.constraints
  rw [satBranch_constraints_iff_run]
  rw [run_eq_flatMap_children W hlive]
  constructor
  · rintro ⟨L, hL, hsatL⟩
    obtain ⟨W', hchild, hrun⟩ := List.mem_flatMap.mp hL
    refine ⟨W', hchild, ?_⟩
    exact (satBranch_constraints_iff_run v W'.todo W'.lits).mpr ⟨L, hrun, hsatL⟩
  · rintro ⟨W', hchild, hsat⟩
    obtain ⟨L, hrun, hsatL⟩ :=
      (satBranch_constraints_iff_run v W'.todo W'.lits).mp hsat
    exact ⟨L, List.mem_flatMap.mpr ⟨W', hchild, hrun⟩, hsatL⟩

/-- Expanding one branch preserves the atomic-accumulator invariant in every child. -/
theorem children_atomicAcc (W : SearchBranch) (hatomic : AtomicBranch W.lits) :
    ∀ W' ∈ children W, AtomicBranch W'.lits := by
  rcases W with ⟨todo, lits⟩
  cases todo with
  | nil => simp [children]
  | cons c rest =>
      rcases c with ⟨S, φ⟩
      cases φ with
      | atom n =>
          intro W' hmem
          simp only [children, List.mem_singleton] at hmem
          subst W'
          intro sφ hsφ
          rcases List.mem_cons.mp hsφ with rfl | hsφ
          · exact ⟨n, rfl⟩
          · exact hatomic _ hsφ
      | neg φ => cases S <;> simpa [children]
      | conj φ ψ => cases S <;> simpa [children]
      | disj φ ψ => cases S <;> simpa [children]
      | oplus φ ψ => cases S <;> simpa [children]

/-- One arbitrary progressing step preserves and reflects forest satisfiability. -/
theorem forestStep_sat_iff (v : Nat → V4) {F F' : SearchForest}
    (hstep : ForestStep F F') : ForestSat v F ↔ ForestSat v F' := by
  cases hstep with
  | @expand pre post W hlive =>
      constructor
      · rintro ⟨X, hmem, hsat⟩
        have hcases : X ∈ pre ∨ X = W ∨ X ∈ post := by simpa using hmem
        rcases hcases with hpre | hEq | hpost
        · exact ⟨X, by simp [hpre], hsat⟩
        · subst X
          obtain ⟨W', hchild, hsat'⟩ :=
            (sat_constraints_iff_children v W hlive).mp hsat
          exact ⟨W', by simp [hchild], hsat'⟩
        · exact ⟨X, by simp [hpost], hsat⟩
      · rintro ⟨X, hmem, hsat⟩
        have hcases : X ∈ pre ∨ X ∈ children W ∨ X ∈ post := by
          simpa [or_assoc] using hmem
        rcases hcases with hpre | hchild | hpost
        · exact ⟨X, by simp [hpre], hsat⟩
        · have hsatW := (sat_constraints_iff_children v W hlive).mpr
              ⟨X, hchild, hsat⟩
          exact ⟨W, by simp, hsatW⟩
        · exact ⟨X, by simp [hpost], hsat⟩

/-- One arbitrary progressing step preserves all atomic accumulators. -/
theorem forestStep_atomicAcc {F F' : SearchForest} (hstep : ForestStep F F') :
    ForestAtomicAcc F → ForestAtomicAcc F' := by
  cases hstep with
  | @expand pre post W hlive =>
      intro hinv W' hmem
      have hcases : W' ∈ pre ∨ W' ∈ children W ∨ W' ∈ post := by
        simpa [or_assoc] using hmem
      rcases hcases with hpre | hchild | hpost
      · exact hinv W' (by simp [hpre])
      · exact children_atomicAcc W (hinv W (by simp)) W' hchild
      · exact hinv W' (by simp [hpost])

namespace ForestReach

/-- Concatenation of two finite progress traces. -/
theorem trans {F G H : SearchForest} (hFG : ForestReach F G)
    (hGH : ForestReach G H) : ForestReach F H := by
  induction hGH with
  | refl => exact hFG
  | tail _ hstep ih => exact .tail ih hstep

/-- A single progress transition as a finite trace. -/
theorem single {F G : SearchForest} (h : ForestStep F G) : ForestReach F G :=
  .tail (.refl F) h

/-- Every finite progress trace preserves and reflects forest satisfiability. -/
theorem sat_iff {F G : SearchForest} (h : ForestReach F G) (v : Nat → V4) :
    ForestSat v F ↔ ForestSat v G := by
  induction h with
  | refl => rfl
  | tail _ hstep ih => exact ih.trans (forestStep_sat_iff v hstep)

/-- Every finite progress trace preserves the atomic-accumulator invariant. -/
theorem atomicAcc {F G : SearchForest} (h : ForestReach F G) :
    ForestAtomicAcc F → ForestAtomicAcc G := by
  induction h with
  | refl => exact id
  | tail _ hstep ih => exact fun hF => forestStep_atomicAcc hstep (ih hF)

end ForestReach

/-- Every nonterminal forest admits a legal progressing successor. -/
theorem exists_forestStep_of_not_terminal {F : SearchForest}
    (h : ¬ ForestTerminal F) : ∃ F', ForestStep F F' := by
  simp only [ForestTerminal, not_forall] at h
  obtain ⟨W, hmem, hlive⟩ := h
  obtain ⟨pre, post, rfl⟩ := List.mem_iff_append.mp hmem
  exact ⟨pre ++ children W ++ post, .expand hlive⟩

/-- A forest is terminal exactly when no progressing transition is enabled. -/
theorem no_forestStep_iff_terminal (F : SearchForest) :
    (¬ ∃ F', ForestStep F F') ↔ ForestTerminal F := by
  constructor
  · intro hnormal
    by_contra hterminal
    exact hnormal (exists_forestStep_of_not_terminal hterminal)
  · intro hterminal
    rintro ⟨F', hstep⟩
    cases hstep with
    | @expand pre post W hlive => exact hlive (hterminal W (by simp))

/-- Every forest has a terminal forest reachable by finitely many progressing steps. -/
theorem exists_terminal_reachable (F : SearchForest) :
    ∃ G, ForestReach F G ∧ ForestTerminal G := by
  apply forestStep_wellFounded.induction F
  intro F ih
  by_cases hterminal : ForestTerminal F
  · exact ⟨F, .refl F, hterminal⟩
  · obtain ⟨F', hstep⟩ := exists_forestStep_of_not_terminal hterminal
    obtain ⟨G, hreach, hGterminal⟩ := ih F' hstep
    exact ⟨G, (ForestReach.single hstep).trans hreach, hGterminal⟩

/-- Classical choice supplies at least one progressing scheduler; all correctness
theorems below quantify over traces and therefore do not depend on this choice. -/
noncomputable def defaultProgressScheduler : ProgressScheduler := fun _ hterminal =>
  ⟨Classical.choose (exists_forestStep_of_not_terminal hterminal),
   Classical.choose_spec (exists_forestStep_of_not_terminal hterminal)⟩

/-- Initial singleton forest for an input branch. -/
def initialForest (B : Branch) : SearchForest := [⟨B, []⟩]

theorem initialForest_atomicAcc (B : Branch) : ForestAtomicAcc (initialForest B) := by
  simp [initialForest, ForestAtomicAcc, AtomicBranch]

theorem initialForest_sat_iff (v : Nat → V4) (B : Branch) :
    ForestSat v (initialForest B) ↔ satBranch v B := by
  simp [initialForest, ForestSat, SearchBranch.constraints]

/-- Thm 4.33: every terminal forest reachable from the input is closed exactly when
the input branch is semantically unsatisfiable. -/
theorem terminal_reachable_closed_iff_unsat {B : Branch} {F : SearchForest}
    (hreach : ForestReach (initialForest B) F)
    (hterminal : ForestTerminal F) :
    ForestClosed F ↔ ∀ v, ¬ satBranch v B := by
  have hatomicF := hreach.atomicAcc (initialForest_atomicAcc B)
  constructor
  · intro hclosed v hsatB
    have hsatInit := (initialForest_sat_iff v B).mpr hsatB
    obtain ⟨W, hW, hsatW⟩ := (hreach.sat_iff v).mp hsatInit
    have htodo : W.todo = [] := hterminal W hW
    have hsatL : satBranch v W.lits := by
      simpa [SearchBranch.constraints, htodo] using hsatW
    exact (atomic_unsat_iff_closed (hatomicF W hW)).mpr (hclosed W hW) v hsatL
  · intro hunsat W hW
    apply (atomic_unsat_iff_closed (hatomicF W hW)).mp
    intro v hsatL
    apply hunsat v
    apply (initialForest_sat_iff v B).mp
    apply (hreach.sat_iff v).mpr
    refine ⟨W, hW, ?_⟩
    have htodo : W.todo = [] := hterminal W hW
    simpa [SearchBranch.constraints, htodo] using hsatL

/-- A terminal output of any progressing scheduler agrees with the declarative tableau
calculus. -/
theorem terminal_reachable_closed_iff_closes {B : Branch} {F : SearchForest}
    (hreach : ForestReach (initialForest B) F)
    (hterminal : ForestTerminal F) : ForestClosed F ↔ Closes B := by
  rw [terminal_reachable_closed_iff_unsat hreach hterminal]
  constructor
  · exact closes_of_unsat
  · exact Nullivance.Metatheory.Closes.unsat

/-- If a reachable terminal forest is not closed, an open atomic leaf supplies an
explicit canonical countervaluation of the original input. -/
theorem terminal_reachable_open_countermodel {B : Branch} {F : SearchForest}
    (hreach : ForestReach (initialForest B) F)
    (hterminal : ForestTerminal F) (hopen : ¬ ForestClosed F) :
    ∃ W ∈ F, ¬ BranchClosed W.lits ∧
      satBranch (canonicalVal W.lits) W.lits ∧
      satBranch (canonicalVal W.lits) B := by
  simp only [ForestClosed, not_forall] at hopen
  obtain ⟨W, hW, hnotClosed⟩ := hopen
  have hatomicF := hreach.atomicAcc (initialForest_atomicAcc B)
  have hsatL := atomic_open_canonical_sat (hatomicF W hW) hnotClosed
  have hsatF : ForestSat (canonicalVal W.lits) F := by
    refine ⟨W, hW, ?_⟩
    have htodo : W.todo = [] := hterminal W hW
    simpa [SearchBranch.constraints, htodo] using hsatL
  have hsatInit := (hreach.sat_iff (canonicalVal W.lits)).mpr hsatF
  exact ⟨W, hW, hnotClosed, hsatL,
    (initialForest_sat_iff (canonicalVal W.lits) B).mp hsatInit⟩

/-- Any two terminal outputs reachable from the same input agree on success, regardless
of the order in which their progressing schedulers selected active branches. -/
theorem terminal_outputs_agree {B : Branch} {F G : SearchForest}
    (hF : ForestReach (initialForest B) F) (hFt : ForestTerminal F)
    (hG : ForestReach (initialForest B) G) (hGt : ForestTerminal G) :
    ForestClosed F ↔ ForestClosed G := by
  exact (terminal_reachable_closed_iff_unsat hF hFt).trans
    (terminal_reachable_closed_iff_unsat hG hGt).symm

/-- Regression witness: a decomposed contradiction closes under the executable
reference search. -/
example :
    referenceCloses
      [(Sign.Tpos, Formula.conj (Formula.atom 0) (Formula.atom 1)),
       (Sign.Tneg, Formula.atom 0)] = true := by
  native_decide

/-- Regression witness: a satisfiable non-atomic branch yields failure rather than
a false proof. -/
example :
    referenceCloses
      [(Sign.Tpos, Formula.disj (Formula.atom 0) (Formula.atom 1))] = false := by
  native_decide

end Nullivance.Operational
