param(
  [string]$OutputPath
)

$projectRoot = Split-Path -Parent $PSScriptRoot
if (-not $OutputPath) {
  $OutputPath = Join-Path $projectRoot 'docs/CLAIM_LEDGER.md'
}

$canonicalFiles = Get-ChildItem -LiteralPath (Join-Path $projectRoot 'docs') -File |
  Where-Object { $_.Name -match '^0[1-5]-.*\.md$' } |
  Sort-Object Name

$headerPattern =
  '^\*\*(Definition|Convention|Lemma|Proposition|Theorem|Corollary|Remark|Conjecture) ' +
  '([0-9]+\.[0-9]+)(.*?)\.\*\* `\[(DRAFT|CONJECTURE|PROVEN|VERIFIED|REFUTED)\]`'

$claims = @()
foreach ($file in $canonicalFiles) {
  $lines = Get-Content -LiteralPath $file.FullName -Encoding utf8
  for ($index = 0; $index -lt $lines.Count; $index++) {
    if ($lines[$index] -notmatch $headerPattern) {
      continue
    }

    $kind = $Matches[1]
    $number = $Matches[2]
    $title = $Matches[3].Trim()
    $status = $Matches[4]
    $end = $index + 1
    while ($end -lt $lines.Count -and $lines[$end] -notmatch $headerPattern) {
      $end++
    }
    $block = ($lines[$index..($end - 1)] -join "`n")

    $claims += [pscustomobject]@{
      Number = $number
      Kind = $kind
      Title = $title
      Status = $status
      Source = "$($file.Name):$($index + 1)"
      LeanPointer = if ($block -match '\*Lean:\*') { 'yes' } else { 'no' }
      Dependencies = if ($block -match '\*Depends on:\*') { 'yes' } else { 'no' }
    }
  }
}

$statusSummary = $claims |
  Group-Object Status |
  Sort-Object Name |
  ForEach-Object { "$($_.Name): $($_.Count)" }

$output = [System.Collections.Generic.List[string]]::new()
$output.Add('# Canonical claim ledger')
$output.Add('')
$output.Add('Generated by `scripts/Update-ClaimLedger.ps1`. Regenerate after adding,')
$output.Add('removing, or changing a numbered canonical item. This ledger inventories')
$output.Add('status and evidence pointers; the canonical statement remains in its source file.')
$output.Add('')
$output.Add("Inventory: $($claims.Count) numbered items. " + ($statusSummary -join '; ') + '.')
$output.Add('')
$output.Add('## Current P0 exceptions')
$output.Add('')
$output.Add('- No numbered P0 correctness exception remains in propositional operational search: arbitrary progressing selection order is `[VERIFIED]` by Theorem 4.33; idle-step weak fairness is explicitly outside its scope.')
$output.Add('- The replay-certificate strengthenings 3.39 and 3.50 are `[REFUTED]` by an admissible nonempty fold-cascade witness; the verified semantic bridges 3.75 and 3.77 are unaffected.')
$output.Add('- The membership-selecting repair is sound, passes the cascade/empty-tail regressions, and is universally complete for admissible ground-closed traces by Conjecture 3.84 and Proposition 3.90; the older ReplayClosesCore claims 3.39/3.50 remain refuted.')
$output.Add('- No unlabelled critical exception is recorded; every numbered item and its current epistemic status appear below.')
$output.Add('')
$output.Add('## Numbered items')
$output.Add('')
$output.Add('| Item | Title | Status | Canonical source | Lean pointer | Dependency pointer |')
$output.Add('|---|---|---|---|---:|---:|')

foreach ($claim in $claims) {
  $safeTitle = $claim.Title.Replace('|', '\|')
  $output.Add("| $($claim.Kind) $($claim.Number) | $safeTitle | ``[$($claim.Status)]`` | ``$($claim.Source)`` | $($claim.LeanPointer) | $($claim.Dependencies) |")
}

$output.Add('')
$output.Add('## Audit rule')
$output.Add('')
$output.Add('A `yes` in the Lean-pointer column records only that the canonical block names')
$output.Add('Lean evidence. It does not grant `[VERIFIED]`; a synchronization audit, proof-hole')
$output.Add('scan, and successful full build are still required by `docs/WORKFLOW.md`.')

$output | Set-Content -LiteralPath $OutputPath -Encoding utf8
